version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    ports:
      - '4321'
    environment:
      POSTGRES_PASSWORD: '4578'
      POSTGRES_USERNAME: 'docker'
      POSTGRES_DATABASE: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:


